FarmFresh/FarmFresh/Controllers/AdminController.cs
using DataAccess;
using DataAccess.DA;
using DataAccess.Model;
using DataAccess.SearchModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace FarmFresh.Controllers
{
    public class AdminController : Controller
    {
        DA_Product da = new DA_Product();
        CommonClass cs = new CommonClass();
        // GET: Admin
        
        public ActionResult ProductListAdmin(SM_Product data)
        {
            List<ProductType> lst = cs.ProductTypeList();
            lst.Add(new ProductType { Value = "all", ProductTypeName = "All" });
            ViewBag.ProductTypeList = lst.OrderBy(a => a.ProductTypeName);
            ViewBag.PackingType = cs.PackingType();
            data.ProductType = null;
            data.TotalPage = cs.TotalPage(da.Count_GetProductsAdmin(data));
            data.TotalCount = da.Count_GetProductsAdmin(data);
            data.CurrentPage = 1;

            return View(data);
        }
        public ActionResult ProductListAdminPartial(string getpassdata)
        {
            List<Product> list = new List<Product>();
            if (!string.IsNullOrEmpty(getpassdata))
            {
                var serializeData = JsonConvert.DeserializeObject<SM_Product>(getpassdata);
                if (serializeData.ProductType == "all")
                    serializeData.ProductType = null;
                list = da.GetProductsAdmin(serializeData);
                ViewBag.CurrentPagePartial = serializeData.CurrentPage - 1;
            }
           
            return PartialView("ProductListAdminPartial",list);
        }
        public  ActionResult GetTotalPage(string getpassdata)
        {
            List<Product> list = new List<Product>();
            int TotalPage = 0;
            if (!string.IsNullOrEmpty(getpassdata))
            {
                var serializeData = JsonConvert.DeserializeObject<SM_Product>(getpassdata);
                if (serializeData.ProductType == "all")
                    serializeData.ProductType = null;
                TotalPage = cs.TotalPage(da.Count_GetProductsAdmin(serializeData));
            }
            return Json(TotalPage, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EditProductForm(string GUID)
        {
            Product data = new Product();
            ViewBag.ProductTypeList = cs.ProductTypeList();
            ViewBag.PackingType = cs.PackingType();
            if (!string.IsNullOrEmpty(GUID))
            {
                data = da.GetProductByGUID(GUID);
                ViewBag.SelectedProductType = data.ProductType;
            }
            return PartialView("EditProductForm", data);
        }

        [HttpPost]
        public async Task<JsonResult> UploadProductPhoto()
        {
            string fileName = string.Empty;
            try
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i]; //Uploaded file
                                                                //Use the following properties to get file's name, size and MIMEType
                    int fileSize = file.ContentLength;
                    fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string mimeType = file.ContentType;
                    System.IO.Stream fileContent = file.InputStream;
                    //To save file, use SaveAs methodC:\Projects\Ant Tech\HIMS\HIMS\HIMS\UploadData\PatientPhoto\
                    file.SaveAs(Server.MapPath("~/ProductUploadPhotos/") + fileName); //File will be saved in application root
                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }

            return Json(fileName);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditProduct(Product data)
        {
            data.ProductType = Request.Form["ProductType"];
            data.PackingType = Request.Form["PackingType"];
            if (!string.IsNullOrEmpty(data.GUID))
            {
                data.CreatedDate = DateTime.Now.ToString("dd/MM/yyyy hh:mm tt");

                bool updated = da.UpdateProduct(data);
                if (updated)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Fail", JsonRequestBehavior.AllowGet);
                }
            }
            else
            {

                data.GUID = Guid.NewGuid().ToString();
                data.CreatedDate = DateTime.Now.ToString("dd/MM/yyyy hh:mm tt");
                data.Status = 1;
                bool added = da.AddProduct(data);
                if (added)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Fail", JsonRequestBehavior.AllowGet);
                }
            }
        }

        public JsonResult DeleteProduct(string GUID)
        {
            bool deleted = da.DeleteProduct(GUID);
            if (deleted)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FarmFresh/FarmFresh/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Model;
using DataAccess.DA;
using System.Threading.Tasks;
using System.IO;
using System.Net;
using DataAccess.Model;

namespace FarmFresh.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
       
        public ActionResult Pagination(int Page, int Count)
        {
            ViewBag.Page = Page;
            ViewBag.Count = Count;
            return PartialView();
        }

        [HttpPost]
        public JsonResult GetProductName(string Prefix)
        {
            //Note : you can bind same list from database  
            List<Product> ObjList = new List<Product>();
            DA_Product daMT = new DA_Product();
            ObjList = daMT.GetAllProducts();
            //Searching records from list using LINQ query  
            var CityList = (from N in ObjList
                            where N.ProductName.ToLower().Contains(Prefix.ToLower())
                            select new { N.ProductName, N.ID });
            return Json(CityList, JsonRequestBehavior.AllowGet);
        }

        
    }
}

FarmFresh/FarmFresh/Controllers/ProductController.cs
using DataAccess.Model;
using DataAccess.SearchModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.DA;
using DataAccess;

namespace FarmFresh.Controllers
{
    public class ProductController : Controller
    {
        DA_Product da = new DA_Product();
        CommonClass cs = new CommonClass();

        // GET: Product
        public ActionResult ProductList()
        {
            return View();
        }

        public ActionResult ProductListPartial(string getpassdata)
        {
            List<Product> list = new List<Product>();
            if (!string.IsNullOrEmpty(getpassdata))
            {
                var serializeData = JsonConvert.DeserializeObject<SM_Search>(getpassdata);
                if (serializeData.SerachType == "onsale")
                {
                    list = da.GetProducts_ByOnSale(serializeData);
                    ViewBag.TotalPagePartial = cs.TotalPage(da.Count_GetProducts_ByOnSale(serializeData));
                }
                else if (serializeData.SerachType == "new")
                {
                    list = da.GetProducts_ByNew(serializeData);
                    ViewBag.TotalPagePartial = cs.TotalPage(da.Count_GetProducts_ByNew(serializeData));
                }
                else if (serializeData.SerachType == "shopbystore")
                {
                    list = da.GetProducts_ByShopByStore(serializeData);
                    ViewBag.TotalPagePartial = cs.TotalPage(da.Count_GetProducts_ByShopByStore(serializeData));
                }
                else
                {
                    list = da.GetProducts_ByProductType(serializeData);
                    ViewBag.TotalPagePartial = cs.TotalPage(da.Count_GetProducts_ByProductType(serializeData));
                }
                ViewBag.CurrentPagePartial = serializeData.CurrentPage - 1;
            }
            return PartialView("ProductListPartial", list);
        }

        public ActionResult ProductDetail(string GUID)
        {
            Product modal = da.GetProductByGUID(GUID);
            return PartialView("ProductDetail", modal);
        }

        public ActionResult SearchMain(string getpassdata)
        {
            List<Product> list = new List<Product>();
            if (!string.IsNullOrEmpty(getpassdata))
            {
                list = da.GetProducts_ByAllPossibleSearch(getpassdata);
            }
            return PartialView("SearchMain", list);
        }


    }
}

FarmFresh/FarmFresh/Views/Admin/EditProductForm.cshtml
@model DataAccess.Model.Product
@using (Html.BeginForm("EditProduct", "Admin", FormMethod.Post, new { id = "EditProduct" }))
{
    <div class="modal-header bg-slate-800" style="border-radius:0">

        @if (string.IsNullOrEmpty(Model.GUID))
        {

            <h5 class="modal-title font-weight-bold">Add Product Form</h5>
        }
        else
        {
            <h5 class="modal-title font-weight-bold">Update Product Form</h5>
        }
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>

    <div class="modal-body">
        <div class="form-group">
            <div class="row">
                <div class="col-sm-12 mt-2">
                    <label class="font-weight-bold">Product Name</label>
                    @Html.TextBoxFor(a => a.ProductName, new { type = "text", @class = "form-control round", placeholder = "", required = "required", autocomplete = "off" })
                    @Html.HiddenFor(a => a.ID)
                    @Html.HiddenFor(a => a.GUID)
                </div>
                <div class="col-sm-6 mt-2">
                    <label class="font-weight-bold">Product Type</label>
                    <select id="ProductType" name="ProductType" class=" form-control">
                        @if (ViewBag.ProductTypeList != null)
                        {
                            foreach (var data in ViewBag.ProductTypeList)
                            {
                                if (Model.ProductType == data.Value)
                                {
                                    <option selected value="@data.Value">@data.ProductTypeName</option>
                                }
                                else
                                {
                                    <option value="@data.Value">@data.ProductTypeName</option>
                                }
                            }
                        }
                    </select>
                </div>
                <div class="col-sm-6 mt-2">
                    <label class="font-weight-bold">Packing Type</label>
                    <select id="PackingType" name="PackingType" class=" form-control">
                        @if (ViewBag.PackingType != null)
                        {
                            foreach (var data in ViewBag.PackingType)
                            {
                                if (Model.PackingType == data)
                                {
                                    <option selected value="@data">@data</option>
                                }
                                else
                                {
                                    <option value="@data">@data</option>
                                }
                            }
                        }
                    </select>
                </div>

                <div class="col-sm-6 mt-2 row">
                    <label class="font-weight-bold col-sm-6 mt-3 ">On Sale !</label>
                    @Html.CheckBoxFor(a => a.OnSale, new { @class = "form-check col-sm-6 mt-4", placeholder = "", autocomplete = "off" })
                </div>
                <div class="col-sm-6 mt-2 row">
                    <label class="font-weight-bold col-sm-7 mt-3 pr-0">Shop By Store</label>
                    @Html.CheckBoxFor(a => a.ShopByStore, new { @class = "form-check col-sm-5 mt-4", placeholder = "", autocomplete = "off" })
                </div>
                @if (Model.ProductPhoto != null)
                {
                    <div class=" col-sm-6 mt-4">
                        @Html.HiddenFor(a => a.ProductPhoto, new { type = "hidden", @class = "form-control hide", placeholder = "", autocomplete = "off", style = "resize:none", id = "ProductPhoto" })

                        <img id="productphotoid" class="img-thumbnail" width="100" height="300" src="~/ProductUploadPhotos/@Model.ProductPhoto" alt="">
                        <input id="upload" class="form-control-file" type="file" onchange="onFileSelected(event)" accept="image/*">
                        <a href="#" id="upload_link" class="btn btn-primary btn-sm">
                            Upload
                        </a>

                    </div>
                }
                else
                {
                    <div class=" col-sm-6 mt-4">
                        @Html.HiddenFor(a => a.ProductPhoto, new { type = "hidden", @class = "form-control hide", placeholder = "", autocomplete = "off", style = "resize:none", id = "ProductPhoto" })

                        <img id="productphotoid" class="img-thumbnail" width="100" height="300" src="~/Resources/placeholder.jpg" alt="">
                        <input id="upload" class="form-control-file" type="file" onchange="onFileSelected(event)" accept="image/*">
                        <a href="#" id="upload_link" class="btn btn-primary btn-sm">
                            Upload
                        </a>

                    </div>
                }

            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancle</button>
        @if (string.IsNullOrEmpty(Model.GUID))
        {
            <button type="submit" onclick="" class="btn btn-primary btn-ladda btn-ladda-spinner" data-spinner-color="#333" data-style="zoom-in"><span class="ladda-label">Save</span></button>
        }
        else
        {
            <button type="submit" onclick="" class="btn btn-primary btn-ladda btn-ladda-spinner" data-spinner-color="#333" data-style="zoom-in"><span class="ladda-label">Edit</span></button>
        }
    </div>
}

FarmFresh/FarmFresh/Views/Admin/ProductListAdmin.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Admin Page";
}

@model DataAccess.SearchModel.SM_Product
<!-- Core JS files -->



<div class="col-lg-12">
    <div class="row">
        <div class=" col-sm-6"><h4 class="panel-title font-weight-bold">Product Control</h4></div>
        <div class=" col-sm-6 text-right"><button class="btn btn-primary  " onclick="Add()"><b><i class="icon icon-add"></i></b>Add New</button></div>
    </div>
    <fieldset>

        <div class="  mt-10 row ">
            <div class="form-group col-lg-3">
                <label class="font-weight-bold">Product Type</label>
                <select id="SearchProductType" name="SearchProductType" class=" form-control">
                    @if (ViewBag.ProductTypeList != null)
                    {
                        foreach (var data in ViewBag.ProductTypeList)
                        {
                            if (Model.ProductType == data.Value)
                            {
                                <option selected value="@data.Value">@data.ProductTypeName</option>
                            }
                            else
                            {
                                <option value="@data.Value">@data.ProductTypeName</option>
                            }
                        }
                    }
                </select>
            </div>
            <div class=" col-lg-6 text-left"><button class="btn btn-outline-info mt-4" type="submit" onclick="Search()"> Search </button></div>
        </div>

    </fieldset>
    <hr />
    <div class="card mt-10 " style="border-radius:10px">
        <div class="table-responsive" style="border-radius:10px">
            <table class="table table-sm">
                <thead class="bg-slate-800">
                    <tr>

                        <th>#</th>
                        <th>Product</th>
                        <th>Photo</th>
                        <th>Product Type</th>
                        <th>Packing Type </th>
                        <th>On Sale </th>
                        <th>Shop By Store </th>
                        @*<th width="5%">UMO</th>
                            <th width="9%">UMO(Description)</th>*@
                        @*<th>Created By/Date</th>*@
                        <th>Created Date</th>
                        <th class="text-center border-right-info">Actions</th>
                    </tr>
                </thead>
                <!-- Table Body -->
                <tbody id="tablebody">
                </tbody>
            </table>
        </div>
    </div>
    <!-- Pagination -->
    <div id="pagination"></div>
    
    <div id="DataEditFormModalBody" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal-label" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div id="EditFormModalBody">
                </div>

            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script src="~/Scripts/sweet_alert.minNew.js"></script>
<script>

        var CurrentPage = @Html.Raw(Json.Encode(Model.CurrentPage));
        var TotalCount = @Html.Raw(Json.Encode(Model.TotalPage));
        var searchData = {
            'ProductID': @Html.Raw(Json.Encode(Model.ProductID)),
            'ProductName': @Html.Raw(Json.Encode(Model.ProductName)),
            'ProductType': @Html.Raw(Json.Encode(Model.ProductType)),
            'TotalCount': @Html.Raw(Json.Encode(Model.TotalCount)),
            'TotalPage': @Html.Raw(Json.Encode(Model.TotalPage)),
            'CurrentPage': @Html.Raw(Json.Encode(Model.CurrentPage)),
    }

    $('#DataEditFormModal').on('hidden.bs.modal', function () {
        $(this).data('modal', null);
        $("#EditFormModalBody").empty();
    });


    $(document).ready(function () {
        showlist("#tablebody", searchData);
    });

    $("#upload_link").on('click', function (e) {
        e.preventDefault();
        $("#upload:hidden").trigger('click');
    });

    function onFileSelected(event) {
        var selectedFile = event.target.files[0];

        var reader = new FileReader();

        var imgtag = document.getElementById("productphotoid");
        imgtag.title = selectedFile.name;

        reader.onload = function (event) {
            imgtag.src = event.target.result;
        };
        var data = new FormData();
        data.append(selectedFile.name, selectedFile);
        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadProductPhoto", "Admin")',
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                $('#ProductPhoto').val(result);
            },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                console.log(err);
            }
        });
        reader.readAsDataURL(selectedFile);
    }

    function Edit(GUID) {

        BindEditForm(GUID, "Edit");
    }
    function Add() {

        BindEditForm("","Add");
    }
    function Search() {
        searchData.ProductType = $("#SearchProductType").val();
        GetTotalPage();
        showlist("#tablebody", searchData);
    }
    function showlist(div, passdata) {
        var data = JSON.stringify(passdata);
            $.ajax({
            cache: false,
            url: '@Url.Action("ProductListAdminPartial", "Admin")',
            contentType: 'application/json; charset=utf-8',
            data: { getpassdata: data},
            beforesend: function () {
                $(div).empty().append('<div class="text-center"><div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div></div>');
                },
            success: function (myData) {
                $(div).empty().append(myData);
                Pagination(CurrentPage, searchData.TotalPage);
                },
            complete: function () {
                }
            });
    }
    function Pagination(Page, Count) {
            $.ajax({
            cache: false,
            url: '@Url.Action("Pagination", "Common")',
            data: { Page: Page, Count: Count},
            //beforeSend: function () {
            //    $(div).empty().append('<div class="text-center"><div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div></div>');
            //},
            success: function (myData) {
                $("#pagination").empty().append(myData);
            },
            complete: function () {
            }
        });
    }
    function GetTotalPage() {
        var data = JSON.stringify(searchData);
            $.ajax({
            cache: false,
            url: '@Url.Action("GetTotalPage", "Admin")',
            data: { getpassdata: data},
            success: function (myData) {
                              searchData.TotalPage = myData;
            },
            complete: function () {
            }
        });
    }

    function Delete(GUID) {
           swal({
                title: "Are you sure?",
                text: "You will not be able to recover this data!",
               type: "warning",
               icon: "warning",
               buttons: true,
               dangerMode: true,})
                .then((willDelete) => {
                    if (willDelete) {
                       $.ajax({
                        cache: false,
                        url: '@Url.Action("DeleteProduct", "Admin")',
                        contentType: 'application/json; charset=utf-8',
                        data: { GUID: GUID},

                        success: function (myData) {
                            if (myData == "Success") {

                                swal("Poof! Your data has been deleted!", {
                                icon: "success",});
                                Pagination(CurrentPage, TotalCount);
                                showlist("#tablebody", searchData);
                            }
                            else {
                                swal("", "Oops! Process Fail !!", "fail");
                            }
                         }

                     });

                    } else {
                        swal("Your data is safe!");
                            }
                });
    }
    function pageFunction(current) {
        searchData.CurrentPage = current;
        CurrentPage = current;
        Pagination(current, TotalCount);
        showlist("#tablebody", searchData);
    }
    function BindEditForm(GUID,Type) {
            $.ajax({
                cache: false,
                url: '@Url.Action("EditProductForm", "Admin")',
                data: { GUID: GUID},
                beforeSend: function () {
                },
                success: function (Data) {
                    $("#EditFormModalBody").empty().append(Data);
                },
                complete: function () {
                    $("#DataEditFormModalBody").modal('show');
                    $('#EditProduct').submit(function (e) {
                        e.preventDefault();
                        $.ajax({
                            cache: false,
                            url: $(this).attr('action'),
                            data: $(this).serialize(),
                            type: "POST",
                            beforeSend: function () {
                                $('#savebtn').empty().append('<span class="spinner icon-spinner4"></span> Saving...');
                                $('#savebtn').prop("disabled", true);
                            },
                            success: function (myData) {
                                if (myData == "Success") {
                                    if (Type == "Add") {
                                        swal("", "Successfully Saved!", "success");
                                    }
                                    else {
                                        swal("", "Successfully Edited !", "success");
                                    }

                                }
                                else {
                                    swal("", "Oops! Process Fail !!", "fail");
                                }
                                $("#DataEditFormModalBody").modal('hide');
                                showlist("#tablebody", searchData);
                            },
                            complete: function () {
                            }
                        });
                    });
                }
            });
    }

     $('#ProductDetail').on('hidden.bs.modal', function () {
        $(this).data('modal', null);
        $("#ProductDetailModal").empty();
    });


    function ProductDetail(GUID) {

            $.ajax({
                cache: false,
                url: '@Url.Action("ProductDetail", "Product")',

                data: { GUID: GUID},
                beforeSend: function () {
                },
                success: function (Data) {
                    $("#ProductDetailModal").empty().append(Data);
                },
                complete: function () {
                    $("#ProductDetail").modal('show');
                }
            });
    }

</script>

FarmFresh/FarmFresh/Views/Admin/ProductListAdminPartial.cshtml
@model  IEnumerable<DataAccess.Model.Product>

@{
    var count = 1;
    var CP = Convert.ToInt32(ViewBag.CurrentPagePartial);
    CP = CP - 1;
    count = (CP * DataAccess.CommonClass.PageSize) + 1;

    foreach (var data in @Model)
    {
        <tr>
            <td>@count</td>
            <td>@data.ProductName </td>
            <td>
                <img src="~/ProductUploadPhotos/@data.ProductPhoto" height="100" width="100" />
            </td>
            <td>
                @{ 
                    var Type = DataAccess.CommonClass.ProductTypeListStatic().Where(a => a.Value == data.ProductType).FirstOrDefault().ProductTypeName;
                }
                @Type
            </td>
            <td>@data.PackingType</td>
            <td>@data.OnSale</td>
            <td>@data.ShopByStore</td>
            <td>@data.CreatedDate</td>
            <td class="text-center">
                <div class="list-icons">
                    <button data-popup="tooltip" title="Update" class="btn btn-sm btn-info " onclick="Edit('@data.GUID')">Update </button>
                    @*<button data-popup="tooltip" title="UOM" class="btn btn-sm btn-icon rounded-round bg-teal-800 " onclick="BindUMO('@data.GUID')"><b><i class="icon-tree7 "></i></b> </button>*@
                    <button data-popup="tooltip" title="Delete" class="btn  btn-sm btn-danger " onclick="Delete('@data.GUID')">Delete </button>
                </div>
            </td>
        </tr>
        count++;
    }
}